#!/bin/bash
set -euv

cd /
svn checkout http://llvm.org/svn/llvm-project/llvm/trunk/ llvm
cd /llvm/tools
svn checkout http://llvm.org/svn/llvm-project/cfe/trunk/ clang
cd /llvm/projects
svn checkout http://llvm.org/svn/llvm-project/compiler-rt/trunk/ compiler-rt

cd /llvm
patch -p0 < /geordi/src/llvm-no-temp-files.patch

mkdir /llvm.build
cd /llvm.build
/llvm/configure --enable-optimized --disable-assertions --enable-targets=x86_64 --disable-docs --disable-terminfo --disable-libedit --disable-backtraces --disable-jit
make -j2
make install

rm -rf /llvm /llvm.build
