#!/bin/bash
set -euv

cd /
wget https://haskell.org/platform/download/8.0.2/haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz
tar xf haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz
./install-haskell-platform.sh

rm install-haskell-platform.sh
rm hp-usr-local.tar.gz
rm haskell-platform-8.0.2-unknown-posix--minimal-x86_64.tar.gz
