#!/bin/sh
rm -f geordi-irc geordi-xmpp geordi-local geordi-testsuite prelude/*.o rt/prelude.a rt/prelude.hpp.gch src/*.o src/*.hi src/*_hsc.* src/Cxx/*.o src/Cxx/*.hi src/Editing/*.o src/Editing/*.hi src/EvalCxx.hs src/Ptrace.hs src/SysCalls.* src/Flock.hs src/Sys.hs
