#!/bin/sh
set -eu
. ./compile-config
cd prelude
$GXX $COMPILE_FLAGS -c prelude.cpp tracked.cpp type_strings.cpp more_ostreaming.cpp
cd ..
rm -f rt/prelude.a
ar -rsc rt/prelude.a prelude/*.o
$GXX $COMPILE_FLAGS -c -x c++-header prelude/prelude.hpp -o rt/prelude.hpp.gch
chmod 644 rt/prelude.a rt/prelude.hpp.gch
cp prelude/terse.hpp rt/
$GXX $COMPILE_FLAGS -fPIC -shared -Wl,-soname,libtpreload.so.0 -o rt/libtpreload.so.0.0 prelude/tpreload.cpp
