#!/bin/sh
set -eu
DATA=`cat prefix`/share/geordi-0
RT="${DATA}/rt"
. "${DATA}/compile-config"
cd prelude
$GXX $COMPILE_FLAGS -c prelude.cpp tracked.cpp type_strings.cpp more_ostreaming.cpp
cd ..
rm -f "${RT}/prelude.a"
ar -rsc "${RT}/prelude.a" prelude/*.o
$GXX $COMPILE_FLAGS -c -x c++-header prelude/prelude.hpp -o "${RT}/prelude.hpp.gch"
chmod 644 "${RT}/prelude.a" "${RT}/prelude.hpp.gch"
cp prelude/terse.hpp "${RT}/"
$GXX $COMPILE_FLAGS -fPIC -shared -Wl,-soname,libtpreload.so.0 -o "${RT}/libtpreload.so.0.0" prelude/tpreload.cpp
