#!/bin/bash -v
echo -e "#include \"prelude.h\"\nGEORDI_PRINT_PRE 9 GEORDI_PRINT_POST" > rt/t.cpp
source compile-config
chroot rt strace -s 3000 -v -q -f -e signal=none -e trace=execve $GXX -Winvalid-pch t.cpp prelude.a $COMPILE_FLAGS $LINK_FLAGS -o t 2>&1 | grep -v ENOENT | runhaskell scripts/processtrace.hs > gcc-execs
